# -*- coding: utf-8 -*-
"""Essen | Flash Sales | 27/28-02-26 | Inc. per Customer segments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlgMs-g-kekGTesmOHiGSSIgRKFuJ_Tv

# Importing Section
"""

from google.colab import files
from google.colab import auth
from oauth2client.client import GoogleCredentials
#GCP Auth
auth.authenticate_user()
!pip install tfcausalimpact #installing the necessary packages

import logging
import pandas as pd
import numpy as np
import warnings
from causalimpact import CausalImpact

import seaborn as sn
import matplotlib.pyplot as plt

from google.colab import auth
import gspread
from google.auth import default

import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe

"""# Loading Customer Segments"""

# 2. Authenticate User
# This will trigger a popup asking you to allow access to your Google Drive/Sheets
print("Authenticating...")
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# 3. Open the Spreadsheet
spreadsheet_url = 'https://docs.google.com/spreadsheets/d/1LNnEj1byzsu7OrYGLsgA3-Pdld0RXBIFj5B-Grl-F_U/edit?gid=523339875#gid=523339875'
# Extract the ID and open
sh = gc.open_by_url(spreadsheet_url)

# 4. Find the specific tab (Worksheet) by GID
# Your URL points to GID '1000028141'. We loop to find the matching sheet.
target_gid = '523339875'
worksheet = None

for ws in sh.worksheets():
    if str(ws.id) == target_gid:
        worksheet = ws
        break

if worksheet:
    print(f"Connected to worksheet: '{worksheet.title}'")

    # 5. Load data into Pandas DataFrame
    rows = worksheet.get_all_values()

    # Note: Using the first row as headers.
    # If your data starts lower, change 'rows[1:]' to 'rows[2:]', etc.
    df_orders = pd.DataFrame(rows[1:], columns=rows[0])

    # Preview the data
    print("Data successfully loaded!")

else:
    print(f"Error: Worksheet with GID {target_gid} not found.")

df_orders.head()

# 1. Convert the column to numeric
# 'coerce' turns anything it can't read as a number (like "N/A" or "None") into NaN
df_orders['totalorders'] = pd.to_numeric(df_orders['totalorders'])

pre_period      =       [pd.to_datetime(date) for date in ['2025-10-01', '2025-12-31']]
post_period     =       [pd.to_datetime(date) for date in ['2026-02-27', '2026-02-28']]

"""# Customer segment = NEW"""

new_df = df_orders[df_orders['base_segment'] == 'new']

new_df.head()

new_df.set_index('date', inplace=True)
n_new = new_df.pivot(columns='citygroup', values='totalorders')
n_new.index = pd.to_datetime(n_new.index)
n_new = n_new.reindex(sorted(n_new.columns,reverse=True),axis=1)
n_new.head()
n_new = n_new.fillna(0)

impact_new = CausalImpact(n_new, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_new.plot()
print(impact_new.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
new_df_summary = impact_new.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
new_df_summary = new_df_summary.reset_index()
new_df_filtered = new_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
new_actual_value = new_df_filtered.loc[0, 'cumulative']
new_prediction_value = new_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
new_df_final = pd.DataFrame({
    'actual': [new_actual_value],
    'prediction': [new_prediction_value]
})

# 4. Add the customer segment as a column.
new_df_final['segment'] = 'New'

"""# Customer segment = REACTIVATED"""

reactivated_df = df_orders[df_orders['base_segment'] == 'reactivated']

reactivated_df.head()

reactivated_df.set_index('date', inplace=True)
n_reactivated = reactivated_df.pivot(columns='citygroup', values='totalorders')
n_reactivated.index = pd.to_datetime(n_reactivated.index)
n_reactivated = n_reactivated.reindex(sorted(n_reactivated.columns,reverse=True),axis=1)
n_reactivated = n_reactivated.fillna(0)

impact_reactivated = CausalImpact(n_reactivated, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_reactivated.plot()
print(impact_reactivated.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
reactivated_df_summary = impact_reactivated.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
reactivated_df_summary = reactivated_df_summary.reset_index()
reactivated_df_filtered = reactivated_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
reactivated_actual_value = reactivated_df_filtered.loc[0, 'cumulative']
reactivated_prediction_value = reactivated_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
reactivated_df_final = pd.DataFrame({
    'actual': [reactivated_actual_value],
    'prediction': [reactivated_prediction_value]
})

# 4. Add the customer segment as a column.
reactivated_df_final['segment'] = 'Reactivated'

"""# Customer segment = EARLY"""

early_df = df_orders[df_orders['base_segment'] == 'early']

early_df.head()

early_df.set_index('date', inplace=True)
n_early = early_df.pivot(columns='citygroup', values='totalorders')
n_early.index = pd.to_datetime(n_early.index)
n_early = n_early.reindex(sorted(n_early.columns,reverse=True),axis=1)
n_early = n_early.fillna(0)

impact_early = CausalImpact(n_early, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_early.plot()
print(impact_early.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
early_df_summary = impact_early.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
early_df_summary = early_df_summary.reset_index()
early_df_filtered = early_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
early_actual_value = early_df_filtered.loc[0, 'cumulative']
early_prediction_value = early_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
early_df_final = pd.DataFrame({
    'actual': [early_actual_value],
    'prediction': [early_prediction_value]
})

# 4. Add the customer segment as a column.
early_df_final['segment'] = 'Early'

"""# Customer segment = ENGAGED"""

engaged_df = df_orders[df_orders['base_segment'] == 'engaged']

engaged_df.head()

engaged_df.set_index('date', inplace=True)
n_engaged = engaged_df.pivot(columns='citygroup', values='totalorders')
n_engaged.index = pd.to_datetime(n_engaged.index)
n_engaged = n_engaged.reindex(sorted(n_engaged.columns,reverse=True),axis=1)
n_engaged = n_engaged.fillna(0)

impact_engaged = CausalImpact(n_engaged, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_engaged.plot()
print(impact_engaged.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
engaged_df_summary = impact_engaged.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
engaged_df_summary = engaged_df_summary.reset_index()
engaged_df_filtered = engaged_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
engaged_actual_value = engaged_df_filtered.loc[0, 'cumulative']
engaged_prediction_value = engaged_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
engaged_df_final = pd.DataFrame({
    'actual': [engaged_actual_value],
    'prediction': [engaged_prediction_value]
})

# 4. Add the customer segment as a column.
engaged_df_final['segment'] = 'Engaged'

"""# Customer segment = LAPSING"""

lapsing_df = df_orders[df_orders['base_segment'] == 'lapsing']

lapsing_df.head()

lapsing_df.set_index('date', inplace=True)
n_lapsing = lapsing_df.pivot(columns='citygroup', values='totalorders')
n_lapsing.index = pd.to_datetime(n_lapsing.index)
n_lapsing = n_lapsing.reindex(sorted(n_lapsing.columns,reverse=True),axis=1)
n_lapsing = n_lapsing.fillna(0)

impact_lapsing = CausalImpact(n_lapsing, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_lapsing.plot()
print(impact_lapsing.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
lapsing_df_summary = impact_lapsing.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
lapsing_df_summary = lapsing_df_summary.reset_index()
lapsing_df_filtered = lapsing_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
lapsing_actual_value = lapsing_df_filtered.loc[0, 'cumulative']
lapsing_prediction_value = lapsing_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
lapsing_df_final = pd.DataFrame({
    'actual': [lapsing_actual_value],
    'prediction': [lapsing_prediction_value]
})

# 4. Add the customer segment as a column.
lapsing_df_final['segment'] = 'Lapsing'

"""# Customer segment = DORMANT"""

dormant_df = df_orders[df_orders['base_segment'] == 'dormant']

dormant_df.head()

dormant_df.set_index('date', inplace=True)
n_dormant = dormant_df.pivot(columns='citygroup', values='totalorders')
n_dormant.index = pd.to_datetime(n_dormant.index)
n_dormant = n_dormant.reindex(sorted(n_dormant.columns,reverse=True),axis=1)
n_dormant = n_dormant.fillna(0)

impact_dormant = CausalImpact(n_dormant, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_dormant.plot()
print(impact_dormant.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
dormant_df_summary = impact_dormant.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
dormant_df_summary = dormant_df_summary.reset_index()
dormant_df_filtered = dormant_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
dormant_actual_value = dormant_df_filtered.loc[0, 'cumulative']
dormant_prediction_value = dormant_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
dormant_df_final = pd.DataFrame({
    'actual': [dormant_actual_value],
    'prediction': [dormant_prediction_value]
})

# 4. Add the customer segment as a column.
dormant_df_final['segment'] = 'Dormant'

"""# Customer segment = PROSPECT


"""

prospect_df = df_orders[df_orders['base_segment'] == 'prospect']

prospect_df.head()

prospect_df.set_index('date', inplace=True)
n_prospect = prospect_df.pivot(columns='citygroup', values='totalorders')
n_prospect.index = pd.to_datetime(n_prospect.index)
n_prospect = n_prospect.reindex(sorted(n_prospect.columns,reverse=True),axis=1)
n_prospect = n_prospect.fillna(0)

impact_prospect = CausalImpact(n_prospect, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_prospect.plot()
print(impact_prospect.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
prospect_df_summary = impact_prospect.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
prospect_df_summary = prospect_df_summary.reset_index()
prospect_df_filtered = prospect_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
prospect_actual_value = prospect_df_filtered.loc[0, 'cumulative']
prospect_prediction_value = prospect_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
prospect_df_final = pd.DataFrame({
    'actual': [prospect_actual_value],
    'prediction': [prospect_prediction_value]
})

# 4. Add the customer segment as a column.
prospect_df_final['segment'] = 'Prospect'

"""# Customer segment = CHURNED"""

churned_df = df_orders[df_orders['base_segment'] == 'churned']

churned_df.head()

churned_df.set_index('date', inplace=True)
n_churned = churned_df.pivot(columns='citygroup', values='totalorders')
n_churned.index = pd.to_datetime(n_churned.index)
n_churned = n_churned.reindex(sorted(n_churned.columns,reverse=True),axis=1)
n_churned = n_churned.fillna(0)

impact_churned = CausalImpact(n_churned, pre_period, post_period, model_args={'fit_model':'hmc'})

impact_churned.plot()
print(impact_churned.summary())

# 1. Extract the summary data from your CausalImpact object
# This pulls the main result metrics (Actual, Prediction, Absolute Effect, Relative Effect, etc.)
churned_df_summary = impact_churned.summary_data

# Reset the index so the row names (Average, Cumulative) become a proper column
churned_df_summary = churned_df_summary.reset_index()
churned_df_filtered = churned_df_summary.loc[0:1, ['cumulative']]

# 2. Extract the individual values
churned_actual_value = churned_df_filtered.loc[0, 'cumulative']
churned_prediction_value = churned_df_filtered.loc[1, 'cumulative']

# 3. Restructure into your desired format
# This creates a new DataFrame with 1 row and 2 columns
churned_df_final = pd.DataFrame({
    'actual': [churned_actual_value],
    'prediction': [churned_prediction_value]
})

# 4. Add the customer segment as a column.
churned_df_final['segment'] = 'Churned'

# 1. Put all your DataFrames into a list
dataframes_to_union = [ new_df_final,
                        reactivated_df_final,
                        early_df_final,
                        engaged_df_final,
                        lapsing_df_final,
                        dormant_df_final,
                        prospect_df_final,
                        churned_df_final]

# 2. Use pd.concat to combine them
# ignore_index=True resets the row numbers so they go 0, 1, 2, 3...
# instead of keeping the original index (0, 0, 0, 0...)
df_combined = pd.concat(dataframes_to_union, ignore_index=True)

df_combined