# -*- coding: utf-8 -*-
"""MAVERICK | Control City Finder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181V0Y0UK51s7xyPQuSP1L17Yx1LVxCrn

# Installing packages
"""

#Packages

from google.colab import files
from google.colab import auth
from oauth2client.client import GoogleCredentials
#GCP Auth
auth.authenticate_user()

import pandas as pd
import numpy as np

import statsmodels.api as sm
from sklearn.model_selection import train_test_split

import seaborn as sns
import matplotlib.pyplot as plt

"""# Loading Data"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery df --project just-data-bq-users
# 
# BEGIN
# 
# DECLARE CM DATE DEFAULT date_sub(date_trunc(current_date(),month), interval 1 month);
# DECLARE PM DATE DEFAULT date_sub(date_trunc(current_date(),month), interval 2 month);
# DECLARE PY DATE DEFAULT date_sub(date_trunc(current_date(),month), interval 13 month);
# 
# 
#     WITH active AS (
#         SELECT fo.restaurantcityid,
#                SUM(fo.nroforders)                                                       AS total_ov,
#                SUM(CASE WHEN OrderType = 'Delivery' THEN fo.nroforders ELSE 0 END)      AS logistic_ov
# 
#         FROM `just-data-warehouse.dwh.fact_order`           AS fo
#         INNER JOIN `just-data-warehouse`.dwh.dim_restaurant AS dr   ON fo.restaurantid  = dr.restaurantid
#         INNER JOIN `just-data-warehouse.dwh.dim_ordertype`  AS dot  ON fo.ordertypeid   = dot.OrderTypeID
# 
#         WHERE   dr.country = 'DE'
#             AND DATE(fo.orderdatetime) >= '2025-01-01'
#         GROUP BY ALL
#     ),
# 
#     expansion_cities AS (
#     SELECT dc.city,
#     CASE            WHEN dc.city = 'Flensburg' THEN CAST('2025-06-18' AS DATE)
#                     WHEN dc.city = 'Aschaffenburg' THEN CAST('2025-07-02' AS DATE)
#                     WHEN dc.city = 'Hanau' THEN CAST('2025-07-03' AS DATE)
#                     WHEN dc.city = 'Schwerin' THEN CAST('2025-07-09' AS DATE)
#                     WHEN dc.city = 'Lüneburg' THEN CAST('2025-07-16' AS DATE)
#                     WHEN dc.city = 'Pforzheim' THEN CAST('2025-07-23' AS DATE)
#                     WHEN dc.city = 'Böblingen' THEN CAST('2025-07-30' AS DATE)
#                     WHEN dc.city = 'Sindelfingen' THEN CAST('2025-07-30' AS DATE)
#                     WHEN dc.city = 'Wolfsburg' THEN CAST('2025-08-05' AS DATE)
#                     WHEN dc.city = 'Delmenhorst' THEN CAST('2025-08-12' AS DATE)
#                     WHEN dc.city = 'Salzgitter' THEN CAST('2025-08-19' AS DATE)
#                     WHEN dc.city = 'Hildesheim' THEN CAST('2025-08-19' AS DATE)
#                     WHEN dc.city = 'Jena' THEN CAST('2025-08-26' AS DATE)
#                     WHEN dc.city = 'Reutlingen' THEN CAST('2025-08-26' AS DATE)
#                     WHEN dc.city = 'Esslingen am Neckar' THEN CAST('2025-08-27' AS DATE)
#                     WHEN dc.city = 'Bergisch Gladbach' THEN CAST('2025-08-27' AS DATE)
#                     WHEN dc.city = 'Siegen' THEN CAST('2025-09-02' AS DATE)
#                     WHEN dc.city = 'Gießen' THEN CAST('2025-09-02' AS DATE)
#                     WHEN dc.city = 'Celle' THEN CAST('2025-09-09' AS DATE)
#                     WHEN dc.city = 'Iserlohn' THEN CAST('2025-09-09' AS DATE)
#                     WHEN dc.city = 'Marl' THEN CAST('2025-09-16' AS DATE)
#                     WHEN dc.city = 'Worms' THEN CAST('2025-09-17' AS DATE)
#                     WHEN dc.city = 'Tübingen' THEN CAST('2025-09-17' AS DATE)
#                     WHEN dc.city = 'Düren' THEN CAST('2025-09-18' AS DATE)
#                     WHEN dc.city = 'Gütersloh' THEN CAST('2025-09-23' AS DATE)
#                     WHEN dc.city = 'Zwickau' THEN CAST('2025-10-08' AS DATE)
#                     WHEN dc.city = 'Lünen' THEN CAST('2025-10-09' AS DATE)
#                     WHEN dc.city = 'Lippstadt' THEN CAST('2025-10-14' AS DATE)
#                     WHEN dc.city = 'Rüsselsheim am Main' THEN CAST('2025-10-15' AS DATE)
#                     WHEN dc.city = 'Dormagen' THEN CAST('2025-10-15' AS DATE)
#                     WHEN dc.city = 'Marburg' THEN CAST('2025-10-21' AS DATE)
#                     WHEN dc.city = 'Neumünster' THEN CAST('2025-10-21' AS DATE)
#                     WHEN dc.city = 'Rheine' THEN CAST('2025-10-29' AS DATE)
#                     WHEN dc.city = 'Sankt Augustin' THEN CAST('2025-10-29' AS DATE)
#                     WHEN dc.city = 'Velbert' THEN CAST('2025-10-30' AS DATE)
#                     WHEN dc.city = 'Gera' THEN CAST('2025-11-05' AS DATE)
#                     WHEN dc.city = 'Villingen-Schwenningen' THEN CAST('2025-11-05' AS DATE)
#                     WHEN dc.city = 'Waiblingen' THEN CAST('2025-11-12' AS DATE)
#                     WHEN dc.city = 'Dessau-Roßlau' THEN CAST('2025-11-19' AS DATE)
#                     WHEN dc.city = 'Neunkirchen' THEN CAST('2025-11-20' AS DATE)
#                     WHEN dc.city = 'Dorsten' THEN CAST('2025-11-26' AS DATE)
#                     WHEN dc.city = 'Arnsberg' THEN CAST('2025-11-26' AS DATE)
#                     WHEN dc.city = 'Minden' THEN CAST('2025-11-27' AS DATE)
#                     WHEN dc.city = 'Solingen' THEN CAST('2025-12-02' AS DATE)
#                     WHEN dc.city = 'Remscheid' THEN CAST('2025-12-02' AS DATE)
#                     WHEN dc.city = 'Fulda' THEN CAST('2025-12-10' AS DATE)
#                     WHEN dc.city = 'Lüdenscheid' THEN CAST('2025-12-11' AS DATE)
#                     WHEN dc.city = 'Bocholt' THEN CAST('2025-12-17' AS DATE)
#                     WHEN dc.city = 'Plauen' THEN CAST('2025-12-17' AS DATE)
#                     END AS launch_date
# 
#     FROM `just-data-warehouse`.dwh.dim_city AS dc
#     WHERE dc.country = 'DE'
#     AND dc.city IN
#                     (   'Flensburg',
#                         'Aschaffenburg',
#                         'Hanau',
#                         'Schwerin',
#                         'Lüneburg',
#                         'Pforzheim',
#                         'Böblingen',
#                         'Sindelfingen',
#                         'Wolfsburg',
#                         'Delmenhorst',
#                         'Salzgitter',
#                         'Hildesheim',
#                         'Jena',
#                         'Reutlingen',
#                         'Esslingen am Neckar',
#                         'Bergisch Gladbach',
#                         'Siegen',
#                         'Gießen',
#                         'Celle',
#                         'Iserlohn',
#                         'Marl',
#                         'Worms',
#                         'Tübingen',
#                         'Düren',
#                         'Gütersloh',
#                         'Zwickau',
#                         'Lünen',
#                         'Lippstadt',
#                         'Rüsselsheim am Main',
#                         'Dormagen',
#                         'Marburg',
#                         'Neumünster',
#                         'Rheine',
#                         'Sankt Augustin',
#                         'Velbert',
#                         'Gera',
#                         'Villingen-Schwenningen',
#                         'Waiblingen',
#                         'Dessau-Roßlau',
#                         'Neunkirchen',
#                         'Dorsten',
#                         'Arnsberg',
#                         'Minden',
#                         'Solingen',
#                         'Remscheid',
#                         'Fulda',
#                         'Lüdenscheid',
#                         'Bocholt',
#                         'Plauen')
# ),
# 
#     OV_CM AS (
#         SELECT fo.restaurantcityid,
#                SUM(fo.nroforders)                                                       AS total_CM_ov
# 
#         FROM `just-data-warehouse.dwh.fact_order`           AS fo
#         INNER JOIN `just-data-warehouse`.dwh.dim_restaurant AS dr   ON fo.restaurantid  = dr.restaurantid
# 
#         WHERE   dr.country = 'DE'
#             AND DATE_TRUNC(fo.orderdatetime, MONTH) = date_sub(date_trunc(current_date(),month), interval 1 month)
#         GROUP BY ALL
#     ),
# 
#     OV_PM AS (
#         SELECT fo.restaurantcityid,
#                SUM(fo.nroforders)                                                       AS total_PM_ov
# 
#         FROM `just-data-warehouse.dwh.fact_order`           AS fo
#         INNER JOIN `just-data-warehouse`.dwh.dim_restaurant AS dr   ON fo.restaurantid  = dr.restaurantid
# 
#         WHERE   dr.country = 'DE'
#             AND DATE_TRUNC(fo.orderdatetime, MONTH) = date_sub(date_trunc(current_date(),month), interval 2 month)
#         GROUP BY ALL
#     ),
# 
#     OV_PY AS (
#         SELECT fo.restaurantcityid,
#                SUM(fo.nroforders)                                                       AS total_PY_ov
# 
#         FROM `just-data-warehouse.dwh.fact_order`           AS fo
#         INNER JOIN `just-data-warehouse`.dwh.dim_restaurant AS dr   ON fo.restaurantid  = dr.restaurantid
# 
#         WHERE   dr.country = 'DE'
#             AND DATE_TRUNC(fo.orderdatetime, MONTH) = date_sub(date_trunc(current_date(),month), interval 13 month)
#         GROUP BY ALL
#     ),
# 
#     population AS (
#     SELECT dz.city,
#            SUM(pop_addressable)                             AS pop_15plus,
#            ROUND(SUM(pop.pop_t1529)/SUM(pop_total),2)       AS t15_29_share,
#            ROUND(SUM(pop.pop_t3044)/SUM(pop_total),2)       AS t30_44_share,
#            ROUND(SUM(pop.pop_t4559)/SUM(pop_total),2)       AS t45_59_share,
#            ROUND(SUM(pop.pop_t60up)/SUM(pop_total),2)       AS t60up_share,
# 
#         FROM `just-data-warehouse`.cma_mbr_population.mbr_population     AS pop
#         INNER JOIN  `just-data-warehouse`.dwh.dim_zipcode                AS dz ON pop.tableau_map_zipcode = dz.zipcode
#         WHERE   pop.country = 'DE'
#                 AND dz.country = 'DE'
#                 AND year =  (SELECT MAX(year) FROM `just-data-warehouse`.cma_mbr_population.mbr_population)
#         GROUP BY 1
#     ),
# 
#     supply AS (
#      SELECT  dr.city,
#              COUNT(dr.restaurantid)                                                        AS onlinepartner,
#              SUM(CASE WHEN dr.chain = '(Not available)'        THEN 1 ELSE 0 END)          AS smb_partner,
#              SUM(CASE WHEN dr.chain != '(Not available)'       THEN 1 ELSE 0 END)          AS chain_partner,
#              SUM(CASE WHEN dr.chain like '%McDonald%'            THEN 1 ELSE 0 END)          AS mcd_partner,
#              SUM(CASE WHEN dr.chain = 'Burger King'            THEN 1 ELSE 0 END)          AS bk_partner,
#              SUM(CASE WHEN dr.chain = 'dean&david'             THEN 1 ELSE 0 END)          AS deandavid_partner,
#              SUM(CASE WHEN dr.chain = 'KFC'                    THEN 1 ELSE 0 END)          AS kfc_partner,
#              SUM(CASE WHEN dr.chain = 'Subway'                 THEN 1 ELSE 0 END)          AS subw_partner,
#              SUM(CASE WHEN dlh.restaurantid IS NOT NULL        THEN 1 ELSE 0 END)          AS lh_partner
# 
#       FROM        `just-data-warehouse`.dwh.dim_restaurant                            AS dr
#       LEFT JOIN   `just-data-warehouse`.sales_analytics_datamarts.dim_local_heroes    AS dlh    ON dlh.restaurantid = dr.restaurantid AND dlh.country IN ('DE', 'DEL')
#       WHERE dr.country = 'DE'
#           AND dr.onlinestatus IN ('Online (temporarily closed)','Online (with Menu)')
#       GROUP BY 1
#     ),
# 
# -- Active Customer and Optin --
#     customer_base AS (
#     SELECT dc.customerhash, --- scv_key
#            dc.optin
# 
#     FROM `just-data-warehouse`.dwh.dim_customer AS dc
#     WHERE dc.country IN ('DE', 'DEL')
#     --    AND dc.customerhash = 'e8c56f4d94c754caf450e205be5f2f09f54ccc84'
#     ),
# 
#     customer_city AS (
#     SELECT DISTINCT
#            skb.scv_key,
#            skb.last_values.order_details.city
# 
#     FROM `just-data-warehouse`.customers.scv_key_base AS skb
#     WHERE skb.customer_details.country IN ('DE', 'DEL')
#  ---   AND skb.scv_key = 'e8c56f4d94c754caf450e205be5f2f09f54ccc84'
#     ),
# 
#     ac_base AS (
#     SELECT
#         cc.city,
#         COUNT(DISTINCT fuac.scv_key)                                 AS unique_active_customer,
#         SUM(CASE WHEN cb.optin = TRUE THEN 1 ELSE 0 END)             AS Sum_opt_in
# 
#     FROM `just-data-warehouse`.core_dwh.fact_unique_active_customer     AS fuac
#     INNER JOIN `just-data-warehouse`.dwh.dim_country                    AS dc ON dc.countryid = fuac.countryid
#     LEFT JOIN customer_base                                             AS cb ON fuac.scv_key = cb.customerhash
#     LEFT JOIN customer_city                                             AS cc ON cc.scv_key = fuac.scv_key
#     WHERE dc.country IN ('DE', 'DEL')
#     AND fuac.snapshotdate = DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -1 DAY)
#     GROUP BY 1
# ),
# 
# --- Supply Scraping ---
# 
#     open_monthly AS (SELECT DATE_TRUNC(fcp.scrape_datetime, MONTH)  AS scrape_datetime,
#                              fcp.place_id
# 
#                       FROM `just-data-warehouse.sda.fact_competitor_place` fcp
#                                LEFT JOIN
#                            `just-data-warehouse.sda.dim_competitor_place` dcp ON dcp.place_id = fcp.place_id
#                       WHERE dcp.country                                     IN ('DE', 'DEL')
#                         AND dcp.company                                     IN ( 'DoorDash', 'Just Eat Takeaway.com', 'Uber')
#                         AND fcp.is_open IS TRUE
#                         AND fcp.scrape_datetime                             >= DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -2 MONTH)
#                      ---   AND dcp.city = 'Berlin'
#                       ),
# 
#    market AS (SELECT om.scrape_datetime
#                      , dcp.country
#                      , dcp.city
#                      , COUNT(DISTINCT dcp.global_place_id) AS market
# 
#                 FROM open_monthly om
#                          LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` dcp
#                                    ON dcp.place_id = om.place_id
#                 GROUP BY 1, 2, 3),
# 
#    scraping AS (SELECT
#                dcp.city
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'DoorDash'                 THEN om.place_id END)  AS WOLT
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'Uber'                     THEN om.place_id END)  AS UBER
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'Just Eat Takeaway.com'    THEN om.place_id END)  AS JET
#              , MIN(m.market)                                                                            AS market_partners
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'Just Eat Takeaway.com'    THEN om.place_id END),
#                              MIN(m.market))                                                                               ,2) AS JET_penetration
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'Uber'                     THEN om.place_id END),
#                              MIN(m.market))                                                                              ,2) AS UBER_penetration
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'DoorDash'                 THEN om.place_id END),
#                              MIN(m.market))                                                                              ,2) AS WOLT_penetration
# 
#         FROM open_monthly om
#                  LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` dcp
#                            ON dcp.place_id = om.place_id
#                  LEFT JOIN market AS m ON om.scrape_datetime = m.scrape_datetime AND dcp.country = m.country AND dcp.city = m.city
# 
#         GROUP BY 1
# ),
# 
#    open_monthly_last_year AS (SELECT DATE_TRUNC(fcp.scrape_datetime, MONTH)  AS scrape_datetime,
#                              fcp.place_id
# 
#                       FROM `just-data-warehouse.sda.fact_competitor_place` fcp
#                                LEFT JOIN
#                            `just-data-warehouse.sda.dim_competitor_place` dcp ON dcp.place_id = fcp.place_id
#                       WHERE dcp.country                                     IN ('DE', 'DEL')
#                         AND dcp.company                                     IN ( 'DoorDash', 'Just Eat Takeaway.com', 'Uber')
#                         AND fcp.is_open IS TRUE
#                         AND fcp.scrape_datetime                             = DATE_ADD(DATE_TRUNC(CURRENT_DATE,MONTH), INTERVAL -13 MONTH)
#                      ---   AND dcp.city = 'Berlin'
#                       ),
# 
#    market_last_year AS (SELECT om.scrape_datetime
#                      , dcp.country
#                      , dcp.city
#                      , COUNT(DISTINCT dcp.global_place_id) AS market
# 
#                 FROM open_monthly_last_year om
#                          LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` dcp
#                                    ON dcp.place_id = om.place_id
#                 GROUP BY 1, 2, 3),
# 
#    scraping_last_year AS (SELECT
#                dcp.city
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'DoorDash'                 THEN om.place_id END)  AS WOLT
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'Uber'                     THEN om.place_id END)  AS UBER
#         --     , COUNT(DISTINCT CASE WHEN dcp.company = 'Just Eat Takeaway.com'    THEN om.place_id END)  AS JET
#              , MIN(m.market)                                                                            AS market_partners
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'Just Eat Takeaway.com'    THEN om.place_id END),
#                              MIN(m.market))                                                                               ,2) AS JET_penetration
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'Uber'                     THEN om.place_id END),
#                              MIN(m.market))                                                                              ,2) AS UBER_penetration
#              , ROUND(SAFE_DIVIDE(
#                              COUNT(DISTINCT CASE WHEN dcp.company = 'DoorDash'                 THEN om.place_id END),
#                              MIN(m.market))                                                                              ,2) AS WOLT_penetration
# 
#         FROM open_monthly_last_year om
#                  LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` dcp
#                            ON dcp.place_id = om.place_id
#                  LEFT JOIN market_last_year AS m ON om.scrape_datetime = m.scrape_datetime AND dcp.country = m.country AND dcp.city = m.city
# 
#         GROUP BY 1
# ),
# 
# 
# ---------takealytics fulfillment type (better data quality than SDA) -------------
#   takealytics_venues    AS (
# 
#         SELECT DATE(last_seen_delivery_ubereats)                                                                                                            AS last_seen_date,
#                SPLIT(venue_id_ubereats, '/')[OFFSET(2)]                                                                                                     AS venue_id,
#                'uber'                                                                                                                                       AS competitor,
#                name_ubereats                                                                                                                                AS venue_name,
#                NULLIF(postcode_ubereats, '')                                                                                                                AS postcode,
#                fulfillment_type_ubereats                                                                                                                    AS fulfillment_type,
#                ROW_NUMBER() over (PARTITION BY venue_id_ubereats, DATE_TRUNC(last_seen_delivery_ubereats, MONTH) ORDER BY last_seen_delivery_ubereats DESC) AS row_num -- take latest scrapped data, like this we exclude different values in columns
# 
# 
#         FROM `just-data.production_external_takealytics.de_places_feed_v1_all_2025`
# 
#         WHERE venue_id_ubereats IS NOT NULL
#           AND venue_id_ubereats <> ''
# 
#         UNION ALL
# 
#         SELECT DATE(last_seen_delivery_wolt)                                                                                                    AS last_seen_date,
#                SPLIT(venue_id_wolt, '/')[OFFSET(2)]                                                                                             AS venue_id,
#                'wolt'                                                                                                                           AS competitor,
#                name_wolt                                                                                                                        AS venue_name,
#                NULLIF(postcode_wolt, '')                                                                                                        AS postcode,
#                fulfillment_type_wolt                                                                                                            AS fulfillment_type,
#                ROW_NUMBER() over (PARTITION BY venue_id_wolt, DATE_TRUNC(last_seen_delivery_wolt, MONTH) ORDER BY last_seen_delivery_wolt DESC) AS row_num -- take latest scrapped data, like this we exclude different values in columns
# 
#         FROM `just-data.production_external_takealytics.de_places_feed_v1_all_2025`
#         WHERE venue_id_wolt IS NOT NULL
#           AND venue_id_wolt <> ''
#     ),
# 
#   comp_log_cities as (
#       SELECT DISTINCT city,
#                       COUNT(DISTINCT CASE WHEN fulfillment_type = 'venue_direct' THEN venue_id END) AS comp_mp_partners,
#                       COUNT(DISTINCT CASE WHEN fulfillment_type = 'platform' THEN venue_id END)     AS comp_log_partners,
#                       COUNT(venue_id)                                                      AS nr_partners
# 
#       FROM takealytics_venues AS ob
#               LEFT JOIN  `just-data-warehouse.dwh.dim_zipcode` AS dz
#                         ON ob.postcode = dz.tableaumapzipcode
# 
#       WHERE 1 = 1
#         --AND city = 'Siegburg'                                          -- testing
#         -- AND competitor = 'uber'
#         AND row_num = 1
#         AND DATE(DATE_TRUNC(ob.last_seen_date, MONTH)) = DATE_SUB( DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 MONTH) -- USE ALL SCRAPING DATA FROM LAST MONTH
# 
#       GROUP BY all
#     ORDER BY 1 DESC
# 
#     ),
# 
#     smb_photo_coverage AS (
#         SELECT dr.city,
#                SUM(CASE WHEN fr.snapshot_dt = CURRENT_DATE-2 THEN fr.nr_of_products_offered_with_pictures END)     AS sum_products_offered_with_pictures,
#                SUM(CASE WHEN fr.snapshot_dt = CURRENT_DATE-2 THEN fr.nr_of_products_offered_with_desc END)         AS sum_products_offered_with_desc,
#                SUM(CASE WHEN fr.snapshot_dt = CURRENT_DATE-2 THEN fr.nr_of_products_offered END)                   AS sum_products_offered
# 
#         FROM        `just-data-warehouse.core_dwh.fact_restaurant_daily_snapshot`   AS fr
#         INNER JOIN `just-data-warehouse`.dwh.dim_restaurant                         AS dr ON fr.restaurantid = dr.restaurantid
# 
#         WHERE       dr.country = 'DE'
#                     AND dr.onlinestatus IN ('Online (with Menu)', 'Online (temporarily closed)')
#                     AND fr.snapshot_dt              = CURRENT_DATE-2
#                     AND dr.chain                    = '(Not available)'
#         GROUP BY ALL
# ),
# 
#     smb_menu_to_transaction_cvr AS (
#     SELECT dr.city,
#            SUM(ga.session_transaction)  AS session_transaction,
#            SUM(ga.session_menu)         AS session_menu
# 
#     FROM `just-data-warehouse`.ubd_datamart.restaurant_funnel_serp_to_order AS ga
#     INNER JOIN `just-data-warehouse.dwh.dim_restaurant`                     AS dr ON ga.source_restaurant_id = dr.sourcerestaurantid AND ga.country = dr.country
# 
#     WHERE DATE(DATE_TRUNC(ga.local_date, MONTH))    = CM
#       AND ga.country                                IN ('DE', 'DEL')
#       AND dr.chain                                  = '(Not available)'
# 
#     GROUP BY ALL
# ),
# 
#     session_orders_CM AS (
#     SELECT  ss.session_id,
#             SUM(ss.kpi.order_count) as orders
#     FROM just-data-warehouse.ubd_datamart.session_summary AS ss
#     WHERE   ss.country = 'DE'
#         AND DATE_TRUNC(ss.local_date, MONTH) = CM
#         AND ss.kpi.order_count  > 0
# 
#     GROUP BY 1
# ),
# 
#     cvr_CM AS (
#     SELECT cs.partner_city_commercial,
#            ROUND(SAFE_DIVIDE(SUM(o.orders),COUNT(cs.session_id)),3) AS cvr_CM
# 
#     FROM just-data-warehouse.cdna.city_sessions                 AS cs
#     LEFT JOIN session_orders_CM                             AS o ON cs.session_id = o.session_id
#     WHERE cs.country = 'DE'
#     AND DATE_TRUNC(cs.local_date, MONTH)  = CM
#     GROUP BY 1
# ),
# 
#     session_orders_PM AS (
#     SELECT  ss.session_id,
#             SUM(ss.kpi.order_count) as orders
#     FROM just-data-warehouse.ubd_datamart.session_summary AS ss
#     WHERE   ss.country = 'DE'
#         AND DATE_TRUNC(ss.local_date, MONTH) = PM
#         AND ss.kpi.order_count  > 0
# 
#     GROUP BY 1
# ),
# 
#     cvr_PM AS (
#     SELECT cs.partner_city_commercial,
#            ROUND(SAFE_DIVIDE(SUM(o.orders),COUNT(cs.session_id)),3) AS cvr_PM
# 
#     FROM just-data-warehouse.cdna.city_sessions                 AS cs
#     LEFT JOIN session_orders_PM                             AS o ON cs.session_id = o.session_id
#     WHERE cs.country = 'DE'
#     AND DATE_TRUNC(cs.local_date, MONTH) = PM
#     GROUP BY 1
# ),
# 
#     session_orders_PY AS (
#     SELECT  ss.session_id,
#             SUM(ss.kpi.order_count) as orders
#     FROM just-data-warehouse.ubd_datamart.session_summary AS ss
#     WHERE   ss.country = 'DE'
#         AND DATE_TRUNC(ss.local_date, MONTH) = PY
#         AND ss.kpi.order_count  > 0
# 
#     GROUP BY 1
# ),
# 
#     cvr_PY AS (
#     SELECT cs.partner_city_commercial,
#            ROUND(SAFE_DIVIDE(SUM(o.orders),COUNT(cs.session_id)),3) AS cvr_PY
# 
#     FROM just-data-warehouse.cdna.city_sessions                 AS cs
#     LEFT JOIN session_orders_PY                             AS o ON cs.session_id = o.session_id
#     WHERE cs.country = 'DE'
#     AND DATE_TRUNC(cs.local_date, MONTH) = PY
#     GROUP BY 1
# ),
# 
# -- get google ratings and reviews at global_place_id level to join with competitor partners
#    google_reviews_ratings AS (SELECT fcp.scrape_datetime,
#                                        dcp.country,
#                                        dcp.city,
#                                        dcp.global_place_id,
#                                        average_rating AS average_google_rating,
#                                        total_reviews  AS total_google_reviews
# 
#                                 FROM `just-data-warehouse.sda.fact_competitor_place` AS fcp
#                                          LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` AS dcp
#                                                    ON dcp.place_id = fcp.place_id
# 
#                                 WHERE dcp.country IN ('DE', 'DEL')
#                                   AND dcp.company = 'Google'
#                                   AND DATE_TRUNC(DATE(fcp.scrape_datetime), MONTH) >=
#                                       '2025-02-01' -- google review data available from
#                                   AND DATE_TRUNC(DATE(fcp.scrape_datetime), MONTH) <
#                                       DATE_TRUNC(DATE(CURRENT_DATE), MONTH))
# 
# -- get competitor partners and join them with google ratings and reviews on global_place_id and scrape_date
#    , open_monthly_base AS (SELECT DATE(fcp.scrape_datetime) AS scrape_datetime,
#                                   dcp.global_place_id,
#                                   fcp.place_id,
#                                   dcp.city,
#                                   grr.average_google_rating,
#                                   grr.total_google_reviews,
#                                   fcp.is_open
# 
#                            FROM `just-data-warehouse.sda.fact_competitor_place` AS fcp
#                                     LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` AS dcp
#                                               ON dcp.place_id = fcp.place_id
#                                     LEFT JOIN google_reviews_ratings AS grr
#                                               ON dcp.global_place_id = grr.global_place_id AND
#                                                  fcp.scrape_datetime = grr.scrape_datetime
# 
#                            WHERE dcp.country = 'DE'
#                              AND dcp.company IN ('DoorDash', 'Just Eat Takeaway.com', 'Uber')
#                              AND DATE_TRUNC(DATE(fcp.scrape_datetime), MONTH) >=
#                                  '2025-02-01' -- google review data available from
#                              AND DATE_TRUNC(DATE(fcp.scrape_datetime), MONTH) < DATE_TRUNC(DATE(CURRENT_DATE), MONTH))
# 
# -- get all market partner and their ratings and reviews by month
#    , market_reviews_ratings_monthly AS (SELECT DATE(DATE_TRUNC(scrape_datetime, MONTH)) AS month,
#                                                global_place_id,
#                                                city,
#                                                CASE
#                                                    WHEN MAX(CASE WHEN is_open IS TRUE THEN 1 ELSE 0 END) = 1 THEN 'OPEN'
#                                                    ELSE 'CLOSED' END                                    AS is_open,
#                                                MAX(total_google_reviews)                                AS total_google_reviews,
#                                                MAX(average_google_rating)                               AS average_google_rating,
#                                                MAX(total_google_reviews) * MAX(average_google_rating)   AS partner_popularity_score
# 
#                                         FROM open_monthly_base
#                                         GROUP BY 1, 2, 3)
# 
# -- calculate avg. ratings and reviews per month and city to use as threshold for quality partners
#    , avg_ratings_reviews AS (SELECT month,
#                                     city,
#                                     ROUND(AVG(total_google_reviews) * AVG(average_google_rating),0) AS city_avg_popularity_score
# 
#                              FROM market_reviews_ratings_monthly
#                              WHERE is_open = 'OPEN'
#                              GROUP BY 1, 2)
# 
# -- get partners by open status per month
#    , open_monthly_2 AS (SELECT DATE(DATE_TRUNC(scrape_datetime, MONTH)) AS month,
#                              place_id,
#                              city,
#                              CASE
#                                  WHEN MAX(CASE WHEN is_open IS TRUE THEN 1 ELSE 0 END) = 1 THEN 'OPEN'
#                                  ELSE 'CLOSED' END                                                  AS is_open,
#                              ROUND(MAX(total_google_reviews) * MAX(average_google_rating),0)        AS partner_popularity_score
# 
#                       FROM open_monthly_base
#                       GROUP BY ALL)
# 
# 
# -- nr. open partners by month, city, and brand
#    , competitors AS (SELECT om.month                            AS month,
#                             CASE
#                                 WHEN dcp.company = 'DoorDash' THEN 'wolt'
#                                 WHEN dcp.company = 'Delivery Hero' THEN 'delivery hero'
#                                 WHEN dcp.company = 'Uber' THEN 'uber'
#                                 WHEN dcp.company = 'Just Eat Takeaway.com' THEN 'jet'
#                                 ELSE dcp.company END            AS brand,
#                             dcp.country,
#                             dcp.city                            AS city,
#                             COUNT(CASE
#                                       WHEN (om.partner_popularity_score >= arr.city_avg_popularity_score)
#                                           THEN om.place_id END) AS popular_partners,
#                             COUNT(om.place_id)                  AS partners
# 
#                      FROM open_monthly_2 om
#                               LEFT JOIN `just-data-warehouse.sda.dim_competitor_place` dcp
#                                         ON dcp.place_id = om.place_id
#                               LEFT JOIN avg_ratings_reviews AS arr
#                                         ON om.month = arr.month AND om.city = arr.city
# 
#                      WHERE om.is_open = 'OPEN'
# 
#                      GROUP BY 1, 2, 3, 4)
# 
# -- market size (open) by month and city
#    , market_2 AS (SELECT mrm.month
#                      , mrm.city                                             AS city
#                      , COUNT(DISTINCT CASE
#                                           WHEN (mrm.partner_popularity_score >= arr.city_avg_popularity_score)
#                                               THEN mrm.global_place_id END) AS popular_market
#                      , COUNT(DISTINCT mrm.global_place_id)                  AS market
# 
#                 FROM market_reviews_ratings_monthly AS mrm
#                          LEFT JOIN avg_ratings_reviews AS arr
#                                    ON mrm.month = arr.month AND mrm.city = arr.city
# 
#                 WHERE mrm.is_open = 'OPEN'
# 
#                 GROUP BY 1, 2)
# 
# -- putting partners by competitor and market size together
#    , base AS (SELECT c.month,
#                      c.city,
#                      c.brand,
#                      c.popular_partners,
#                      m.popular_market,
#                      LAG(c.popular_partners, 1)
#                          OVER (PARTITION BY c.city,
#                              c.brand
#                              ORDER BY c.month) AS pop_partners_PM,  -- previous month
#                      LAG(m.popular_market, 1)
#                          OVER (PARTITION BY c.city,
#                              c.brand
#                              ORDER BY c.month) AS pop_market_PM,    -- previous month
#                      LAG(c.popular_partners, 3)
#                          OVER (PARTITION BY c.city,
#                              c.brand
#                              ORDER BY c.month) AS pop_partners_june, -- previous month
#                      LAG(m.popular_market, 3)
#                          OVER (PARTITION BY c.city,
#                              c.brand
#                              ORDER BY c.month) AS pop_market_june,   -- previous month
# 
#               FROM competitors AS c
#                        LEFT JOIN market_2 AS m
#                                  ON c.month = m.month AND c.city = m.city
# ),
# 
#     pop_penetration AS (
#         SELECT city,
#                SUM(CASE
#                        WHEN brand = 'jet'
#                            THEN popular_market END)                                                            AS popular_market_CM,
#                -- sept.
#                SUM(CASE
#                        WHEN brand = 'uber'
#                            THEN ROUND(SAFE_DIVIDE(popular_partners, popular_market), 3) END)                   AS uber_pop_penetration_CM,
#                SUM(CASE
#                        WHEN brand = 'wolt'
#                            THEN ROUND(SAFE_DIVIDE(popular_partners, popular_market), 3) END)                   AS wolt_pop_penetration_CM,
#                SUM(CASE
#                        WHEN brand = 'jet'
#                            THEN ROUND(SAFE_DIVIDE(popular_partners, popular_market), 3) END)                   AS jet_pop_penetration_CM,
#                -- aug.
#                SUM(CASE
#                        WHEN brand = 'uber'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_PM, pop_market_PM), 3) END)                   AS uber_pop_penetration_PM,
#                SUM(CASE
#                        WHEN brand = 'wolt'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_PM, pop_market_PM), 3) END)                   AS wolt_pop_penetration_PM,
#                SUM(CASE
#                        WHEN brand = 'jet'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_PM, pop_market_PM), 3) END)                   AS jet_pop_penetration_PM,
#                -- june
#                SUM(CASE
#                        WHEN brand = 'uber'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_june, pop_market_june), 3) END)                 AS uber_pop_penetration_june,
#                SUM(CASE
#                        WHEN brand = 'wolt'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_june, pop_market_june), 3) END)                 AS wolt_pop_penetration_june,
#                SUM(CASE
#                        WHEN brand = 'jet'
#                            THEN ROUND(SAFE_DIVIDE(pop_partners_june, pop_market_june), 3) END)                 AS jet_pop_penetration_june,
# 
#         FROM base AS b
# 
#         WHERE month = CM
#         GROUP BY ALL
# )
# 
#     SELECT DISTINCT
#            city_tier,
#            dc.city,
#            CASE WHEN cex.city IS NOT NULL THEN 'Expansion City' ELSE NULL END   AS expansion_city,
#            cex.launch_date                                                      AS expansion_launch_date,
#            CASE WHEN cov.total_ov       > 0 THEN 'active' ELSE 'not active' END AS are_we_active,
#            CASE WHEN cov.logistic_ov    > 0 THEN 'logistic active' ELSE 'no logistic active' END AS are_we_active_with_logistic,
#            pop_15plus,
#            t15_29_share,
#            t30_44_share,
#            t45_59_share,
#            t60up_share,
#            onlinepartner,
#            lh_partner,
#            smb_partner,
#            chain_partner,
#            ac.unique_active_customer,
#            sc.market_partners,
# 
#            CASE WHEN sc.JET_penetration > 1 THEN 1 ELSE  sc.JET_penetration END AS JET_penetration,
#            CASE WHEN sc.UBER_penetration > 1 THEN 1 ELSE sc.UBER_penetration END AS UBER_penetration,
#            CASE WHEN sc.WOLT_penetration > 1 THEN 1 ELSE sc.WOLT_penetration END AS WOLT_penetration,
# 
#            ov_CM.total_CM_ov,
#            ROUND(SAFE_DIVIDE((ov_CM.total_CM_ov - ov_PY.total_PY_ov),ov_PY.total_PY_ov),2) AS OV_yoy,
# 
#            cs25.cvr_CM,
#            ROUND((cs25.cvr_CM-cs24.cvr_PY)*100,2) AS cvr_yoy,
#            ROUND(SAFE_DIVIDE(sum_products_offered_with_pictures, sum_products_offered),2)                 AS smb_photo_coverage,
#            ROUND(SAFE_DIVIDE(sum_products_offered_with_desc, sum_products_offered),2)                     AS smb_desc_coverage,
# 
#            CASE WHEN pp.jet_pop_penetration_CM  >1 THEN 1 ELSE pp.jet_pop_penetration_CM END AS   jet_pop_penetration_CM,
#            CASE WHEN pp.uber_pop_penetration_CM >1 THEN 1 ELSE pp.uber_pop_penetration_CM END AS  uber_pop_penetration_CM,
#            CASE WHEN pp.wolt_pop_penetration_CM >1 THEN 1 ELSE pp.wolt_pop_penetration_CM END AS  wolt_pop_penetration_CM,
# 
#            CASE WHEN clog.comp_log_partners    > 0 THEN 'comp logistic active' ELSE 'no comp logistic active' END AS comp_log_active,
# 
#     FROM `just-data-warehouse.country_analytics_hub.dim_reported_city`      AS drc
#     LEFT JOIN `just-data-warehouse`.dwh.dim_city                            AS dc       ON drc.cityid           = dc.cityid
#     LEFT JOIN active                                                        AS cov      ON drc.cityid           = cov.restaurantcityid
#     LEFT JOIN population                                                    AS pop      ON dc.city              = pop.city
#     LEFT JOIN supply                                                        AS su       ON dc.city              = su.city
#     LEFT JOIN ac_base                                                       AS ac       ON dc.city              = ac.city
#     LEFT JOIN scraping                                                      AS sc       ON dc.city              = sc.city
#     LEFT JOIN scraping_last_year                                            AS scly     ON dc.city              = scly.city
#     LEFT JOIN comp_log_cities                                               AS clog     ON dc.city              = clog.city
#     LEFT JOIN OV_CM                                                      AS ov_CM  ON drc.cityid           = ov_CM.restaurantcityid
#     LEFT JOIN OV_PM                                                      AS ovaug25  ON drc.cityid           = ovaug25.restaurantcityid
#     LEFT JOIN OV_PY                                                      AS ov_PY  ON drc.cityid           = ov_PY.restaurantcityid
#     LEFT JOIN expansion_cities                                              AS cex      ON dc.city              = cex.city
#     LEFT JOIN smb_photo_coverage                                            AS pc       ON dc.city              = pc.city
#     LEFT JOIN smb_menu_to_transaction_cvr                                   AS mttc     ON dc.city              = mttc.city
#     LEFT JOIN cvr_CM                                                    AS cs25     ON dc.city              = cs25.partner_city_commercial
#     LEFT JOIN cvr_PM                                                     AS ca25     ON dc.city              = ca25.partner_city_commercial
#     LEFT JOIN cvr_PY                                                    AS cs24     ON dc.city              = cs24.partner_city_commercial
#     LEFT JOIN pop_penetration                                               AS pp       ON dc.city              = pp.city
# 
#     WHERE   drc.country = 'DE'
#         AND dc.country = 'DE'
#         AND city_tier IN ('TIER 2', 'TIER 3', 'TIER 4','TIER 5','TIER 6')
#     ORDER BY pop_15plus DESC;
# 
# END;

"""# Data Transformation"""

df.head()

df.expansion_city = df.expansion_city.fillna('Non Expansion')

df = df.drop(columns=['expansion_launch_date'],axis=1)

df = df.fillna(0)
df = pd.get_dummies(df, columns=['expansion_city', 'are_we_active', 'are_we_active_with_logistic', 'comp_log_active'])

df.head()



"""# Defining Maverick Cities"""

Dortmund  = df.loc[df.city == 'Dortmund'].copy()
Dresden   = df.loc[df.city == 'Dresden'].copy()
Essen     = df.loc[df.city == 'Essen'].copy()

"""# KNN"""

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors


def find_closest_cities(df, target_city, target_city_name, n_neighbors=26):
  numerical_cols = df.select_dtypes(include=['number']).columns.tolist()
  boolean_cols = df.select_dtypes(include=['bool']).columns.tolist()

  # Combine numerical and boolean columns, then remove 'city'
  all_numeric_and_bool_cols = numerical_cols + boolean_cols
  if 'city' in all_numeric_and_bool_cols:
      all_numeric_and_bool_cols.remove('city')

  df_numeric = df[all_numeric_and_bool_cols].copy()
  for col in boolean_cols:
      if col in df_numeric.columns:
          df_numeric[col] = df_numeric[col].astype(int)

  # Ensure 'city' column is not in city_numeric as well
  city_numeric = target_city[all_numeric_and_bool_cols].copy()
  for col in boolean_cols:
      if col in city_numeric.columns:
          city_numeric[col] = city_numeric[col].astype(int)

  # Initialize the StandardScaler
  scaler = StandardScaler()

  # Fit the scaler on the main DataFrame and transform both DataFrames
  df_scaled = scaler.fit_transform(df_numeric)
  city_scaled = scaler.transform(city_numeric)

  # Convert scaled arrays back to DataFrames for easier handling (optional but good practice for readability)
  df_scaled = pd.DataFrame(df_scaled, columns=df_numeric.columns)
  city_scaled = pd.DataFrame(city_scaled, columns=city_numeric.columns)

  # Initialize NearestNeighbors.
  knn = NearestNeighbors(n_neighbors=n_neighbors, algorithm='auto')

  # Fit KNN model on the scaled main DataFrame
  knn.fit(df_scaled)

  # Find the 25 closest cities
  distances, indices = knn.kneighbors(city_scaled)

  # Get the indices of the closest cities in the original DataFrame
  closest_cities_indices = indices.flatten()

  # Exclude target cities itself from the list of closest cities
  # We need the original index in df_numeric to exclude it correctly
  city_original_index_in_df = df[df['city'] == target_city_name].index[0]

  # Find the position of target's original index within the closest_cities_indices array
  try:
      city_position_in_neighbors = list(df.index[closest_cities_indices]).index(city_original_index_in_df)
      # Remove target from the list
      closest_cities_indices = [idx for i, idx in enumerate(closest_cities_indices) if i != city_position_in_neighbors]
  except ValueError: # Target might not be in the top n_neighbors if n_neighbors is small
      pass

  # Select the top 25 closest cities
  closest_cities_df = df.iloc[closest_cities_indices[:n_neighbors]]

  return closest_cities_df

Dortmund_knn = find_closest_cities(df, Dortmund, 'Dortmund')
Dresden_knn = find_closest_cities(df, Dresden, 'Dresden')
Essen_knn = find_closest_cities(df, Essen, 'Essen')

"""# Order Trend Comparison"""

# Commented out IPython magic to ensure Python compatibility.
# %%bigquery df_orders --project just-data-bq-users
# 
# SELECT
#   partner.geo.city
#   , date_trunc(order_date, week(monday)) as week_date
#   , count(distinct orderid) as orders
# FROM
#   `just-data-warehouse.country_analytics_hub.obt_order`
# where
#   country.country in ('DE','DEL')
#   and date_trunc(order_date,month) >= date_sub(date_trunc(current_date(),month), interval 13 month)
#   and date_trunc(order_date,month) < date_trunc(current_date(),month)
#   and customer.customerid <> '-1'
#   and order_attributes.ordertype in ('Delivery','Restaurant Delivery')
#   and order_attributes.delivery_status not in ('delivery cancelled')
#   and partner.geo.city is not null
# group by all
# order by 1,2

df_orders_pivot = df_orders.pivot_table(index='week_date', columns='city', values='orders')
df_orders_pivot = df_orders_pivot.fillna(0)

city_list = ['Dortmund']
temp_list = Dortmund_knn.city.unique()
for city in temp_list:
    if city not in city_list:
        city_list.append(city)

filtered_df_orders_pivot = df_orders_pivot.loc[:,city_list].copy()
correl_matrix = filtered_df_orders_pivot.corr()
control_group = correl_matrix.loc[correl_matrix['Dortmund'] >= 0.8,'Dortmund'].index.to_list()

plt.figure(figsize=(12, 10))
sns.heatmap(correl_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Orders by City')
plt.show()


plt.figure(figsize=(12, 10))
dfl = df_orders.loc[df_orders['city'].isin(control_group)].copy()
sns.lineplot(data=dfl, x='week_date', y='orders', hue = 'city')
plt.show()

control_group

city_list = ['Dresden']
temp_list = Dortmund_knn.city.unique()
for city in temp_list:
    if city not in city_list:
        city_list.append(city)

filtered_df_orders_pivot = df_orders_pivot.loc[:,city_list].copy()
correl_matrix = filtered_df_orders_pivot.corr()
control_group = correl_matrix.loc[correl_matrix['Dresden'] >= 0.8,'Dresden'].index.to_list()

plt.figure(figsize=(12, 10))
sns.heatmap(correl_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Orders by City')
plt.show()


plt.figure(figsize=(12, 10))
dfl = df_orders.loc[df_orders['city'].isin(control_group)].copy()
sns.lineplot(data=dfl, x='week_date', y='orders', hue = 'city')
plt.show()

control_group

city_list = ['Essen']
temp_list = Dortmund_knn.city.unique()
for city in temp_list:
    if city not in city_list:
        city_list.append(city)

filtered_df_orders_pivot = df_orders_pivot.loc[:,city_list].copy()
correl_matrix = filtered_df_orders_pivot.corr()
control_group = correl_matrix.loc[correl_matrix['Essen'] >= 0.8,'Essen'].index.to_list()

plt.figure(figsize=(12, 10))
sns.heatmap(correl_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Orders by City')
plt.show()


plt.figure(figsize=(12, 10))
dfl = df_orders.loc[df_orders['city'].isin(control_group)].copy()
sns.lineplot(data=dfl, x='week_date', y='orders', hue = 'city')
plt.show()

control_group